name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version (e.g., v1.0.0)"
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build and package binaries
        run: npm run pkg

      - name: Rename binaries
        run: |
          mkdir -p release-assets
          cp bin/macos/hfjscli release-assets/hfjscli-macos
          cp bin/linux/hfjscli release-assets/hfjscli-linux
          cp bin/windows/hfjscli.exe release-assets/hfjscli-windows.exe

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: Release ${{ github.event.inputs.version }}
          prerelease: true
          generate_release_notes: true
          files: |
            release-assets/hfjscli-macos
            release-assets/hfjscli-linux
            release-assets/hfjscli-windows.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
